name: Compile with SourceMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.11", "1.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "SCRIPTING_PATH=$GITHUB_WORKSPACE/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compiling plugins
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTING_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTING_PATH }}/
